# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'My Corne'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left","corne_right"]'
      kconfig: '["CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y/nCONFIG_BT_CTLR_TX_PWR_PLUS_8=y"]'
      alphas: '["QWERTY"]'
      nav: '["vi"]'
      
      
